# Generated by Django 4.2.3 on 2023-08-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=25)),
                ("team_logo", models.ImageField(upload_to="team_logos/")),
                ("manager_fname", models.CharField(max_length=25)),
                ("manager_lname", models.CharField(max_length=25)),
                ("manager_number", models.BigIntegerField()),
                ("manager_email", models.EmailField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("player_id", models.AutoField(primary_key=True, serialize=False)),
                ("player_fname", models.CharField(max_length=25)),
                ("player_lname", models.CharField(max_length=25)),
                ("player_age", models.IntegerField()),
                ("player_number", models.IntegerField()),
                ("player_email", models.EmailField(max_length=25)),
                ("player_image", models.ImageField(upload_to="player_images/")),
                (
                    "team_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="basketball.team",
                    ),
                ),
            ],
        ),
    ]
