# Generated by Django 4.2.3 on 2023-08-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "team_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("team_name", models.CharField(max_length=25)),
                ("team_logo", models.ImageField(upload_to="")),
                ("manager_name", models.CharField(max_length=25)),
                ("manager_number", models.BigIntegerField()),
                ("manager_email", models.CharField(max_length=25)),
                ("wins", models.IntegerField()),
                ("loses", models.IntegerField()),
            ],
        ),
    ]
