# Generated by Django 4.2.3 on 2023-08-29 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("game_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_1_score", models.IntegerField()),
                ("team_2_score", models.IntegerField()),
                ("game_status", models.CharField(max_length=20)),
                ("game_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=25)),
                ("team_logo", models.ImageField(upload_to="team_logos/")),
                ("manager_fname", models.CharField(max_length=25)),
                ("manager_lname", models.CharField(max_length=25)),
                ("manager_number", models.IntegerField()),
                ("manager_email", models.EmailField(max_length=254)),
                ("wins", models.IntegerField(blank=True, null=True)),
                ("loses", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScoreKeeper",
            fields=[
                ("keeper_id", models.AutoField(primary_key=True, serialize=False)),
                ("keeper_name", models.CharField(max_length=25)),
                ("keeper_number", models.BigIntegerField()),
                ("keeper_email", models.EmailField(max_length=25)),
                ("keeper_username", models.CharField(max_length=25)),
                ("keeper_password", models.CharField(max_length=50)),
                (
                    "game_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="basketball.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("player_id", models.AutoField(primary_key=True, serialize=False)),
                ("player_fname", models.CharField(max_length=25)),
                ("player_lname", models.CharField(max_length=25)),
                ("player_age", models.DateField()),
                ("player_number", models.IntegerField()),
                ("player_email", models.EmailField(max_length=25)),
                ("player_image", models.ImageField(upload_to="player_images/")),
                ("field_goals", models.IntegerField(blank=True, null=True)),
                ("field_goals_percentage", models.FloatField(blank=True, null=True)),
                ("three_pointers", models.IntegerField(blank=True, null=True)),
                ("three_pointers_percentage", models.FloatField(blank=True, null=True)),
                ("free_throws", models.IntegerField(blank=True, null=True)),
                ("free_throws_percentage", models.FloatField(blank=True, null=True)),
                ("rebounds", models.IntegerField(blank=True, null=True)),
                ("assists", models.IntegerField(blank=True, null=True)),
                ("steals", models.IntegerField(blank=True, null=True)),
                ("blocks", models.IntegerField(blank=True, null=True)),
                ("turnovers", models.IntegerField(blank=True, null=True)),
                ("points", models.IntegerField(blank=True, null=True)),
                (
                    "team_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="basketball.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="team_1_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_1_games",
                to="basketball.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="team_2_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_2_games",
                to="basketball.team",
            ),
        ),
    ]
