# Generated by Django 4.2.3 on 2023-08-01 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("admin_name", models.CharField(max_length=25)),
                ("admin_number", models.BigIntegerField()),
                ("admin_email", models.EmailField(max_length=25)),
                ("admin_username", models.CharField(max_length=25)),
                ("admin_password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("game_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_1_score", models.IntegerField()),
                ("team_2_score", models.IntegerField()),
                ("game_status", models.CharField(max_length=20)),
                ("game_date", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="team",
            name="manager_email",
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_logo",
            field=models.ImageField(upload_to="team_logos/"),
        ),
        migrations.CreateModel(
            name="ScoreKeeper",
            fields=[
                ("keeper_id", models.AutoField(primary_key=True, serialize=False)),
                ("keeper_name", models.CharField(max_length=25)),
                ("keeper_number", models.BigIntegerField()),
                ("keeper_email", models.EmailField(max_length=25)),
                ("keeper_username", models.CharField(max_length=25)),
                ("keeper_password", models.CharField(max_length=50)),
                (
                    "game_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="basketball.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("player_id", models.AutoField(primary_key=True, serialize=False)),
                ("player_name", models.CharField(max_length=25)),
                ("player_age", models.IntegerField()),
                ("player_number", models.IntegerField()),
                ("player_email", models.EmailField(max_length=25)),
                ("player_image", models.ImageField(upload_to="player_images/")),
                ("field_goals", models.IntegerField()),
                ("field_goals_percentage", models.FloatField()),
                ("three_pointers", models.IntegerField()),
                ("three_pointers_percentage", models.FloatField()),
                ("free_throws", models.IntegerField()),
                ("free_throws_percentage", models.FloatField()),
                ("rebounds", models.IntegerField()),
                ("assists", models.IntegerField()),
                ("steals", models.IntegerField()),
                ("blocks", models.IntegerField()),
                ("turnovers", models.IntegerField()),
                ("points", models.IntegerField()),
                (
                    "team_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="basketball.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="team_1_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_1_games",
                to="basketball.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="team_2_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_2_games",
                to="basketball.team",
            ),
        ),
    ]
