# Generated by Django 4.2.3 on 2023-08-02 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0002_admin_game_alter_team_manager_email_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
        migrations.RemoveField(
            model_name="player",
            name="team_id",
        ),
        migrations.RemoveField(
            model_name="scorekeeper",
            name="game_id",
        ),
        migrations.DeleteModel(
            name="Game",
        ),
        migrations.DeleteModel(
            name="Player",
        ),
        migrations.DeleteModel(
            name="ScoreKeeper",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
