# Generated by Django 4.2.3 on 2023-08-30 16:10

import basketball.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0002_team_team_abbreviation_alter_game_game_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="score_keeper",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="basketball.scorekeeper",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_date",
            field=models.DateField(validators=[basketball.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_status",
            field=models.CharField(
                choices=[
                    ("soon", "Soon"),
                    ("q1", "Quarter 1"),
                    ("q2", "Quarter 2"),
                    ("halftime", "Halftime"),
                    ("q3", "Quarter 3"),
                    ("q4", "Quarter 4"),
                    ("final", "Final"),
                ],
                default="Soon",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="assists",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="blocks",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="field_goals",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="field_goals_percentage",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="free_throws",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="free_throws_percentage",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="points",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="rebounds",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="steals",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="three_pointers",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="three_pointers_percentage",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="turnovers",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="loses",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="wins",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
