# Generated by Django 4.2.3 on 2023-08-30 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0003_game_score_keeper_alter_game_game_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="score_keeper",
        ),
    ]
