# Generated by Django 4.2.3 on 2023-08-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="assists",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="blocks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="field_goals",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="field_goals_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="free_throws",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="free_throws_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="points",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="rebounds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="steals",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="three_pointers",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="three_pointers_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="turnovers",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="loses",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="wins",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
