# Generated by Django 4.2.3 on 2023-08-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0005_remove_player_field_goals_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="field_goals_percentage",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="free_throws_percentage",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="three_pointers_percentage",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
