# Generated by Django 4.2.3 on 2023-08-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0007_player_player_shirt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="player_shirt",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
