# Generated by Django 4.2.4 on 2023-08-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=12)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("blog_id", models.AutoField(primary_key=True, serialize=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("number_likes", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("title", models.CharField(max_length=255)),
                ("edited", models.BooleanField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.user"
                    ),
                ),
            ],
        ),
    ]
