# Generated by Django 4.2.4 on 2023-08-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_user_age_alter_user_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("number_likes", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("title", models.CharField(max_length=255)),
                ("edited", models.BooleanField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.user"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
